-- Beldex Loyalty Program listing.
-- Referral link: https://quest.beldex.io/loyalty?referral_code=ZD32WC7N
-- 20% referral bonus on direct referrals, 5% from their referrals.
-- Image deployed at /airdrops/beldex-loyalty-program.png.

insert into public.airdrops (
  title, slug, description, category, chain, status, steps,
  reward_estimate, redirect_url, launch_date, expiry_date, featured,
  cover_image_url
) values (
  'Beldex: Loyalty Program Points Farm',
  'beldex-loyalty-program',
  'Beldex has launched a Loyalty Program where users earn BDX Points for completing tasks and staying active in the ecosystem. Points climb the leaderboard and may qualify for future BDX rewards or an airdrop, though the exact Points-to-BDX conversion has not been announced yet.

The referral system is one of the stronger incentive structures in the program: you earn 20% of the Points generated by your direct referrals, plus 5% from their referrals. This means consistent referral activity compounds your Points balance without requiring additional on-chain work.

Use a separate wallet when participating, and access the program only through official links. As with any points program, there is no guarantee of a specific BDX conversion rate until officially announced.',
  'DeFi',
  null,
  'active',
  '[
    {"title": "Connect your wallet to the Loyalty Program", "description": "Visit [quest.beldex.io/loyalty](https://quest.beldex.io/loyalty?referral_code=ZD32WC7N) through our referral link and connect your wallet. Use a dedicated wallet rather than your main wallet."},
    {"title": "Complete available and daily tasks", "description": "Work through all available tasks on [quest.beldex.io/loyalty](https://quest.beldex.io/loyalty?referral_code=ZD32WC7N) and return each day to complete daily tasks. Consistent daily activity is the most reliable way to stack Points."},
    {"title": "Earn extra Points through referrals", "description": "Share your own referral link from [quest.beldex.io/loyalty](https://quest.beldex.io/loyalty?referral_code=ZD32WC7N) with others. You earn 20% of Points from direct referrals and 5% from their referrals, so the bonus compounds as your network grows."},
    {"title": "Climb the leaderboard", "description": "Monitor your position on the leaderboard at [quest.beldex.io/loyalty](https://quest.beldex.io/loyalty?referral_code=ZD32WC7N). Higher leaderboard positions are typically weighted more heavily in final reward distributions."}
  ]'::jsonb,
  'BDX Points toward potential future airdrop (conversion rate not yet announced)',
  'https://quest.beldex.io/loyalty?referral_code=ZD32WC7N',
  null,
  null,
  true,
  '/airdrops/beldex-loyalty-program.png'
)
on conflict (slug) do update set
  description = excluded.description,
  steps = excluded.steps,
  status = excluded.status,
  cover_image_url = excluded.cover_image_url;

insert into public.airdrop_images (airdrop_id, storage_path, url, sort_order)
select a.id, 'external/beldex-loyalty-program.png', '/airdrops/beldex-loyalty-program.png', 0
from public.airdrops a
where a.slug = 'beldex-loyalty-program'
  and not exists (
    select 1 from public.airdrop_images i
    where i.airdrop_id = a.id and i.storage_path = 'external/beldex-loyalty-program.png'
  );
